# Generated by Django 5.0.2 on 2024-03-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('security_key', models.CharField(max_length=255)),
            ],
        ),
    ]
