# Generated by Django 5.0.2 on 2024-03-04 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='installation_script',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='security_key',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='compagnie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='akevision_rest.compagnie'),
        ),
    ]
