# Generated by Django 5.0.3 on 2024-03-08 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0002_compagnie_client_installation_script_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='installation_script',
        ),
        migrations.AddField(
            model_name='client',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='compagnie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akevision_rest.compagnie'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='security_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='compagnie',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
