# Generated by Django 5.0.3 on 2024-03-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0003_remove_client_installation_script_client_os_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='compagnie',
        ),
        migrations.RemoveField(
            model_name='client',
            name='os',
        ),
    ]
