# Generated by Django 5.0.3 on 2024-03-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0004_remove_client_compagnie_remove_client_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='security_key',
        ),
    ]
