# Generated by Django 5.0.3 on 2024-03-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0006_client_compagnie'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='os',
            field=models.CharField(blank=True, choices=[('Linux', 'Linux'), ('Windows', 'Windows')], max_length=10, null=True),
        ),
    ]
