# Generated by Django 5.0.3 on 2024-03-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0007_client_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ipv4',
            field=models.CharField(blank=True, choices=[('Linux', 'Linux'), ('Windows', 'Windows')], max_length=15, null=True),
        ),
    ]
