# Generated by Django 5.0.3 on 2024-03-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0008_client_ipv4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ipv4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
