# Generated by Django 5.0.3 on 2024-03-12 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0009_alter_client_ipv4'),
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auth_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='authtoken.token'),
        ),
    ]
