# Generated by Django 5.0.3 on 2024-03-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0010_client_auth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='auth_token',
        ),
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
