# Generated by Django 5.0.3 on 2024-03-14 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0014_alter_client_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='client',
            name='refresh_token',
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='client_acces_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_refresh_token', to='akevision_rest.client'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='client_refresh_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_access_token', to='akevision_rest.client'),
        ),
    ]
