# Generated by Django 5.0.3 on 2024-08-28 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0015_remove_client_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameWebsite', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('alerte', models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10, null=True)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akevision_rest.groupewebsite')),
            ],
            options={
                'unique_together': {('nameWebsite', 'groupe')},
            },
        ),
    ]
