# Generated by Django 5.0.3 on 2024-08-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0016_groupewebsite_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='ssl_expiration',
            field=models.IntegerField(null=True),
        ),
    ]
