# Generated by Django 5.0.3 on 2024-09-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0017_website_ssl_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='couleur',
            field=models.CharField(blank=True, choices=[('rouge', 'Rouge'), ('orange', 'Orange'), ('vert', 'Vert'), ('gris', 'Gris')], max_length=10, null=True),
        ),
    ]
