# Generated by Django 5.0.3 on 2024-09-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0018_website_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='last_verification',
            field=models.DateField(blank=True, null=True),
        ),
    ]
