# Generated by Django 5.0.3 on 2024-09-20 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0019_website_last_verification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='client',
            name='compagnie',
        ),
        migrations.RemoveField(
            model_name='refreshtoken',
            name='client_refresh_token',
        ),
        migrations.AddField(
            model_name='compagnie',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('os', models.CharField(blank=True, choices=[('Linux', 'Linux'), ('Windows', 'Windows')], max_length=10, null=True)),
                ('last_communication', models.DateTimeField(auto_now_add=True, null=True)),
                ('address_mac', models.CharField(blank=True, max_length=255, null=True)),
                ('compagnie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akevision_rest.compagnie')),
            ],
            options={
                'unique_together': {('name', 'compagnie')},
            },
        ),
        migrations.DeleteModel(
            name='AccessToken',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
