# Generated by Django 5.0.3 on 2024-09-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0020_alter_client_unique_together_remove_client_compagnie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compagnie',
            name='token',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
