# Generated by Django 5.0.3 on 2024-09-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0021_alter_compagnie_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compagnie',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
