# Generated by Django 5.0.3 on 2024-09-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0022_alter_compagnie_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
