# Generated by Django 5.0.3 on 2024-09-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0024_rename_compagnie_poste_compagnie_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poste',
            old_name='compagnie_id',
            new_name='compagnie',
        ),
        migrations.AlterUniqueTogether(
            name='poste',
            unique_together={('name', 'compagnie')},
        ),
    ]
