# Generated by Django 5.0.3 on 2024-09-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0025_rename_compagnie_id_poste_compagnie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poste',
            old_name='compagnie',
            new_name='compagnie_id',
        ),
        migrations.AlterUniqueTogether(
            name='poste',
            unique_together={('name', 'compagnie_id')},
        ),
    ]
