# Generated by Django 5.0.3 on 2024-09-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0026_rename_compagnie_poste_compagnie_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poste',
            unique_together={('address_mac', 'compagnie_id')},
        ),
    ]
