# Generated by Django 5.0.3 on 2024-09-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0027_alter_poste_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='aes_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
