# Generated by Django 5.0.3 on 2024-09-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0028_poste_aes_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='last_communication',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
