# Generated by Django 5.0.3 on 2024-09-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0029_alter_poste_last_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='is_connected',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
