# Generated by Django 5.0.3 on 2024-09-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0030_poste_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='cpu_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poste',
            name='ram_usage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
