# Generated by Django 5.0.3 on 2024-09-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0031_poste_cpu_usage_poste_ram_usage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poste',
            unique_together=set(),
        ),
    ]
