# Generated by Django 5.0.3 on 2024-09-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0032_alter_poste_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_version', models.CharField(max_length=255)),
            ],
        ),
    ]
