# Generated by Django 5.0.3 on 2024-09-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0033_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.AddField(
            model_name='poste',
            name='version_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
