# Generated by Django 5.0.3 on 2024-09-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akevision_rest', '0034_delete_agent_poste_version_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_version', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='poste',
            name='version_agent',
        ),
    ]
